name: "📑 Add Content"
description: "Add missing content to 30-Days-Of-CPP."
labels: ["content"]
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start

        - [ ] Check the [existing issues](https://github.com/subhadipbhowmik/30-Days-Of-CPP/issues)
        - [ ] I have read the [contributing guidelines](https://github.com/subhadipbhowmik/30-Days-Of-CPP/blob/main/CONTRIBUTING.md)

        ---
  # - type: input
  #   id: page-url
  #   attributes:
  #     label: Site URL
  #     description: The URL of the page where you found the issue
  #   validations:
  #     required: true
  # -- BEGIN fields that correspond to `page-report.yml` —-

  - type: dropdown
    id: day-selection
    attributes:
      label: Select the Day of Content
      options:
        - "Day 1"
        - "Day 2"
        - "Day 3"
        - "Day 4"
        - "Day 5"
        - "Day 6"
        - "Day 7"
        - "Day 8"
        - "Day 9"
        - "Day 10"
        - "Day 11"
        - "Day 12"
        - "Day 13"
        - "Day 14"
        - "Day 15"
        - "Day 16"
        - "Day 17"
        - "Day 18"
        - "Day 19"
        - "Day 20"
        - "Day 21"
        - "Day 22"
        - "Day 23"
        - "Day 24"
        - "Day 25"
        - "Day 26"
        - "Day 27"
        - "Day 28"
        - "Day 29"
        - "Day 30"
        - "others"
    validations:
      required: true

  - type: textarea
    id: missing
    attributes:
      label: "What information is missing?"
    validations:
      required: true

  # -- END fields that correspond to `page-report.yml` —-
